### ISSUE TITLE
`data` and `error` cannot be `undefined` by themselves

### ISSUE THREAD

**Issue by lqdsld** [Kong/swrv#113] opened 2020-11-25 10:17 UTC
## Problem

```ts
interface SomeDataType {
  foo: string;
}

async function fetcher(): Promise<SomeDataType> {
  return { foo: 'test' }
}

const { data, error } = useSWRV('some-key', fetcher);

// const data: Ref<SomeDataType | undefined> | undefined
// const error: Ref<any> | undefined
```

Why can the values `data` and` error` themselves be `undefined`? This is not really what is happening. They are always some kind of `Ref` with values, they cannot be `undefined` by themselves. The code snippets below confirm this.

```ts
// https://github.com/Kong/swrv/blob/03b853191cb00d48f51f8edbdbbe3216e8847bf5/src/use-swrv.ts#L203

stateRef = reactive({
  data: undefined,
  error: undefined,
  isValidating: true,
  key: null
}) as StateRef<Data, Error>

// -- snip --

// https://github.com/Kong/swrv/blob/03b853191cb00d48f51f8edbdbbe3216e8847bf5/src/use-swrv.ts#L389

const res: IResponse = {
  ...toRefs(stateRef),
  mutate: (data, opts: revalidateOptions) => revalidate(data, {
    ...opts,
    forceRevalidate: true
  })
}

return res
```

This code shows that `data` and `error` will always be `Ref<Data>` and `Ref<Error>`, not `Ref<Data> | undefined` and `Ref<Error> | undefined`.

I think the `IResponse` interface should be fixed:

```ts
// now
export interface IResponse<Data = any, Error = any> {
  data?: Ref<Data | undefined>;
  error?: Ref<Error | undefined>;
  isValidating: Ref<boolean>;
  mutate: () => Promise<void>;
}

// should be
export interface IResponse<Data = any, Error = any> {
  data: Ref<Data | undefined>;
  // ^ remove '?'
  error: Ref<Error | undefined>;
  // ^ remove '?'
  isValidating: Ref<boolean>;
  mutate: () => Promise<void>;
}
```

Anyway, thanks for the `swrv`, it's great!

**Comment by darrenjennings** [comment] 2020-11-25 15:25
This is a duplicate of https://github.com/Kong/swrv/issues/74. @lqdsld can you provide a reproduction repo that shows the type error?

**Closed** 2020-12-05 03:14 UTC
