### ISSUE TITLE
Cannot read property '$isServer' of null

### ISSUE THREAD

**Issue by ushironoko** [Kong/swrv#66] opened 2020-07-27 15:42 UTC
I'm trying out swrv in the following environment.
- vite.
- swrv@beta
- axios@latest

Use axios as a swrv fetcher. (Like the nuxt example.)
However, this did not work. When I tried to run it, I got the following error in the console.

```
runtime-dom.esm-bundler-9cc07ca3.js:1258 TypeError: Cannot read property '$isServer' of null
    at useSWRV (swrv.js:137)
    at useRequest (fetch.ts?t=1595862507218:12)
    at Proxy.getPokeData (App.vue:22)
    at _createVNode.onClick._cache.<computed>. _cache.<computed> (App.vue:40)
    at callWithErrorHandling (runtime-dom.esm-bundler-9cc07ca3.js:1199)
    at callWithAsyncErrorHandling (runtime-dom.esm-bundler-9cc07ca3.js:1208)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler-9cc07ca3.js:7481)
```

I ran `getCurrentInstance` and checked, the `vm.$isServer` does not exist.

Am I doing something wrong? Or will swrv + axios not work in a vite environment?

My repository is here. Thanks for the great effort.
https://github.com/ushironoko/swrv-example

**Comment by darrenjennings** [comment] 2020-07-27 19:48
@ushironoko you must use the v3 beta. The installation section of the readme shows how to pull from npm and has a link to our Vite example:

https://github.com/Kong/swrv#installation

**Comment by ushironoko** [comment] 2020-07-28 12:30
@darrenjennings 
I lowered the version of the package associated with vue to match the example, but the result was the same.
Reproduction is available in my [repository](https://github.com/ushironoko/swrv-example/blob/master/package.json).

**Comment by darrenjennings** [comment] 2020-07-28 13:24
Oh I see now @ushironoko you are trying to use swrv inside of an instance method. This issue is actually a duplicate of #40  

See explanation here: https://github.com/Kong/swrv/issues/40#issuecomment-624992291

**Comment by ushironoko** [comment] 2020-07-28 14:35
@darrenjennings 
A perfect example of a perfect answer. Thank you!

**Closed** 2020-07-28 20:46 UTC
